### ISSUE TITLE
Update doc to transifex in a more frequent way like QGEP

### ISSUE THREAD

**Issue by ponceta** [qwat/docs#18]
As discussed with @m-kuhn 

https://github.com/QGEP/docs/commit/11fec125dd711b5874fe671eb9f18bbfbb183402#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34

**Comment by m-kuhn** [comment]
qwat docs and qgep docs are currently structured in a different way:

compare:

- https://github.com/qwat/docs/tree/gh-pages
- https://github.com/qgep/docs/tree/gh-pages

qwat has a doc release per version, qgep one single release for "master"

- is the versioning for the qwat doc a defined process? I.e. is the release management defined so this is taken care of?
- are there links to tagged versions (in the plugin, website, ...)?
- how is the translation handled?
  - only master is pushed as source translation?
  - are the versioned releases redeployed somehow when more translation becomes available?
- should we align the qgep and qwat doc schemes while reworking this?

**Comment by ponceta** [comment]
As you mention QWAT doc was initially designed to reflect QWAT version state.

I would prefer a single master doc approach like qgep with only master as a reference.

This would imply that when we write some documentation about a new functionnality, we also mention what version is required to benefit from it.

QWAT and QGEP should work in the same way for the documentation process so we are not lost when updating it. (Since it is mainly the same people who are updating the documentation)
