### ISSUE TITLE
Enable Czech language

### ISSUE THREAD

**Issue by trendspotter** [qwat/docs#23]
Hi, 
translating QWAT Doc is done. Please enable it on doc pages. 
Please enable Czech translation of plugin on Transifex.

Thanks, best regards, 
Jiri

**Comment by ponceta** [comment]
Hi,

We currently face a bug with transifex documentations but we will publish is as soon as it is solved!

Do you know any Czech folks using QWAT?

Translating QWAT datamodel value lists and QGIS project would then be meaningfull!

Best regards!
Arnaud
